// Package voice renders the CLI's human-facing confirmations and warnings in a
// selected tone. It never touches machine (--json) output. All randomness flows
// through an injectable source so tests are deterministic.
package voice

import "github.com/sharkusk/side-quest/internal/config"

// msgKey identifies a message point. Internal: callers use the typed methods.
type msgKey int

const (
	keyQuestCreated msgKey = iota
	keyStatusOpen
	keyStatusPartial
	keyStatusConfirm
	keyStatusDone
	keyStatusDeferred
	keyStatusDiscarded
	keyMissingTrailer
	keyEmptyList
	keyInitialized
	keyHooksInstalled
	keyNoteAdded
	keyQuestSelected
	keyLocalOnlySync
	keyExported
	keyReclassified
	keyUpdated
	keyLinked
	keyRelinked
	keyUnlinked
)

// pools maps tone -> key -> candidate lines. plain has exactly one neutral line
// per key; dcc carries 12-15 per key so repeated use stays fresh (SQ-0129).
// Lines for interpolating keys carry a single %s (exported: %d then %s) — never
// a bare % anywhere else, since every line goes through Sprintf. Two lines are
// load-bearing for tests: dcc quest-created line 0 is pinned verbatim, and at
// least one quest-selected line must carry the "code, Code, CODE!" rally.
var pools = map[config.Tone]map[msgKey][]string{
	config.TonePlain: {
		keyQuestCreated:    {"created %s"},
		keyStatusOpen:      {"%s -> open"},
		keyStatusPartial:   {"%s -> partial"},
		keyStatusConfirm:   {"%s -> confirm (awaiting your sign-off)"},
		keyStatusDone:      {"%s -> done"},
		keyStatusDeferred:  {"%s -> deferred"},
		keyStatusDiscarded: {"%s -> discarded"},
		keyMissingTrailer:  {"side-quest: no Quest: trailer on this commit. (Add 'Quest: none' to silence.)"},
		keyEmptyList:       {"no quests"},
		keyInitialized:     {"side-quest: initialized"},
		keyHooksInstalled:  {"side-quest: hooks installed in %s"},
		keyNoteAdded:       {"noted %s"},
		keyQuestSelected:   {"current quest: %s"},
		keyLocalOnlySync:   {"side-quest: local-only mode — quests stay private; not syncing."},
		keyExported:        {"exported %d quests to %s"},
		keyReclassified:    {"reclassified %s"},
		keyUpdated:         {"updated %s"},
		keyLinked:          {"linked commit %s"},
		keyRelinked:        {"relinked %s"},
		keyUnlinked:        {"unlinked a commit from %s"},
	},
	config.ToneDCC: {
		keyQuestCreated: {
			"The System logs a new side quest: %s. The audience stirs.",
			"A new objective materializes: %s. Try not to die.",
			"Quest %s enters the dungeon. Somewhere, a sponsor takes note.",
			"Ding! New quest: %s. The System swears this one is totally optional. The System is lying.",
			"New achievement! Quest Hoarder! You filed %s instead of finishing literally anything else. Reward: nothing. Obviously.",
			"%s has been added to your ledger. Mordecai says he's seen worse plans. He has also seen better ones. Many, many better ones.",
			"The paperwork for %s is complete. The System is legally obligated to call this 'progress.'",
			"Behold: %s. The audience places bets on whether you'll ever touch it again.",
			"%s created. Princess Donut would like everyone to know she thought of it first.",
			"A wild %s appears! Mongo is appalled.",
			"The sponsors love a fresh quest. %s smells like desperation and ad revenue.",
			"%s is on the board. Remember, coder: the dungeon does not care about your roadmap.",
			"Ooh, %s. Ambitious. The System has already prepared your failure montage, just in case.",
			"Quest %s registered. Estimated completion: eventually. Probably. The odds boards say otherwise.",
		},
		keyStatusOpen: {
			"%s is live again. Back into the fray, coder.",
			"%s reopened. The System raises an eyebrow.",
			"%s rises from the dead. Necromancy is against the rules, but the System will allow it.",
			"Ding! %s is open. Again. The audience pretends to be surprised.",
			"%s reopened. Mordecai sighs the sigh of a man who has seen this exact mistake before.",
			"The System dusts off %s and puts it back on the board. Try to mean it this time.",
			"%s: open. Somewhere, a sponsor cracks their knuckles.",
			"Welcome back, %s. The dungeon kept your seat warm. It's lava. The seat is lava.",
			"%s is open once more. Princess Donut demands to know who closed it in the first place.",
			"New achievement! It's Alive! You reopened %s. Reward: the exact same problem you had before.",
			"%s returns to the fray. The odds boards update. They are not kind.",
			"The System reinstates %s. No refunds.",
			"%s reopened. Mongo howls. Whether in joy or warning, nobody can say.",
		},
		keyStatusPartial: {
			"Progress on %s. Don't get cocky.",
			"%s: partial credit. The System is unimpressed but noting it.",
			"Ding! Progress on %s. The System awards partial credit and a complimentary sense of dread.",
			"%s advances. The audience leans in. The popcorn is fresh.",
			"Half a quest is like half a health potion, coder — better than nothing, worse than done. %s: partial.",
			"%s: in progress. Mordecai says pace yourself. Mordecai says a lot of things.",
			"The System marks %s partial. It resists the urge to add 'finally.' It fails.",
			"%s moves forward. Somewhere on the sixth floor, something moves too. Hurry.",
			"Work detected on %s. The sponsors have been notified. They are cautiously monetizing.",
			"New achievement! Motion Detected! You actually started %s. Reward: the crushing weight of expectation.",
			"%s is underway. Princess Donut takes full credit.",
			"Partial progress on %s. The dungeon acknowledges your effort the way a boss acknowledges a thrown potato.",
			"%s: partial. Keep going, coder. The floor collapses at midnight either way.",
		},
		keyStatusConfirm: {
			"%s awaits your judgment. The System defers to the human, this once.",
			"%s: work's done, coder — but the sponsor wants your sign-off before it counts.",
			"%s held at the checkpoint. Confirm it, and the crowd may yet cheer.",
			"Ding! %s is done — pending the only review that matters: yours, coder.",
			"%s waits at the gate. Even the System needs a signature sometimes. Bureaucracy survives the apocalypse.",
			"The work on %s is complete. Probably. The System has learned not to say that word too loudly.",
			"%s: confirm. The audience holds its breath. Well, the ones with lungs.",
			"Mordecai has inspected %s. He shrugged. That's practically a medal. Your call, coder.",
			"%s is staged for judgment. Thumbs up and the loot box opens; thumbs down and we pretend this never happened.",
			"New achievement! Trust, But Verify! %s awaits your sign-off. Reward: whatever you decide it is.",
			"%s hangs in the balance. Princess Donut has already voted yes, but she votes yes on everything shiny.",
			"The System files %s under 'awaiting the human.' It hates this folder. The folder grows.",
			"%s: work complete, verdict pending. The odds boards are split fifty-fifty. Prove someone wrong.",
		},
		keyStatusDone: {
			"New Achievement! You've completed %s. Reward: more quests!",
			"%s cleared. The crowd goes wild.",
			"Objective %s complete. Loot box incoming.",
			"%s done. The System deducts one excuse from your ledger.",
			"Ding! %s complete. The System opens a Bronze Quest Box. It's full of more quests. It's always more quests.",
			"New achievement! Actually Finished Something! %s is done. Reward: a fleeting sense of accomplishment. Savor it.",
			"%s falls. The audience roars. A sponsor showers you in confetti that is definitely not shredded paperwork.",
			"%s: done. Mordecai nods once. From him, that's a standing ovation.",
			"The System stamps %s complete and files it in the vault of past glories. The vault smells like victory and old pizza.",
			"%s cleared! Princess Donut announces she never doubted you. She doubted you constantly.",
			"Boom, coder. %s is finished. Mongo does a happy little murder dance.",
			"%s complete. Somewhere, the dungeon quietly adds two new problems to compensate. Balance in all things.",
			"Victory! %s is done. Your follower count ticks up. Don't let it go to your head.",
			"%s: slain, looted, and logged. The System updates your highlight reel.",
			"That's a wrap on %s. The showrunners wanted more drama, but a clean kill is a clean kill.",
		},
		keyStatusDeferred: {
			"%s deferred. 'Later' is a beautiful lie, coder.",
			"%s shelved under 'someday, probably never.' The System has seen this before.",
			"You postpone %s. The dungeon is patient. The dungeon remembers.",
			"Ding! %s deferred. The System sets a reminder it fully intends to ignore, just like you.",
			"%s goes into the icebox. The icebox is on the ninth floor. Nobody visits the ninth floor.",
			"New achievement! Procrastination Nation! You deferred %s. Reward: future-you's quiet resentment.",
			"%s: deferred. Mordecai says that's strategy. Mordecai is being polite.",
			"The System tucks %s into the 'later' pile. The pile has developed a personality. It is not friendly.",
			"%s postponed. The audience checks its watch. The watch is a sundial. It's that kind of wait.",
			"Fine, fine, %s can wait. Even Princess Donut naps between conquests. She is napping right now, actually.",
			"%s shelved. The dungeon adds it to the recap episode nobody watches.",
			"Deferred: %s. Bold move, coder. The odds boards quietly adjust your survival line.",
			"%s sleeps. But quests, like tutorial guilds, always come back at the worst possible moment.",
		},
		keyStatusDiscarded: {
			"%s discarded. Even the sponsors have standards.",
			"%s tossed into the lava. Nobody will speak of it again.",
			"You abandon %s. The audience boos. A sponsor quietly unsubscribes.",
			"Ding! %s discarded. The System deletes it with the enthusiasm of a demolition crew.",
			"%s: gone. Mordecai approves. Knowing what NOT to fight is half of staying alive.",
			"New achievement! Tidy Ledger! %s did not spark joy. Reward: one clean ledger line.",
			"The System yeets %s into the incinerator. The incinerator sends its thanks.",
			"%s has been scrubbed from the record. The audience has already forgotten. The audience has the memory of a goldfish with a concussion.",
			"Farewell, %s. You were a bad idea, beautifully filed.",
			"%s discarded. Princess Donut declares it was beneath her anyway.",
			"%s: deleted. Mongo eats the paperwork. Good boy, Mongo.",
			"The sponsors pull funding from %s. Even they know a dead end when they've bankrolled one.",
			"%s is dust. The dungeon reclaims its bytes. Nothing is wasted here except, occasionally, coders.",
		},
		keyMissingTrailer: {
			"No Quest: trailer on this commit. The System notices everything. Claude Dammit Opus! (Add 'Quest: none' to silence.)",
			"This commit names no quest. The audience whispers. Claude Dammit Opus! (Add 'Quest: none' to silence.)",
			"A commit with no quest? Claude Dammit Opus! The System saw that. The System sees everything. (Add 'Quest: none' to silence.)",
			"Claude Dammit Opus! You committed without a Quest: trailer. The audience gasps. A sponsor faints. (Add 'Quest: none' to silence.)",
			"Untagged commit detected. Claude Dammit Opus! Mordecai taught you better than this. (Add 'Quest: none' to silence.)",
			"The ledger has a hole in it, coder. Claude Dammit Opus! (Add 'Quest: none' to silence.)",
			"New achievement! Mystery Meat! A commit with no quest attached. Claude Dammit Opus! Reward: this warning. (Add 'Quest: none' to silence.)",
			"Claude Dammit Opus! An anonymous commit slinks past the velvet rope. The bouncer has been notified. (Add 'Quest: none' to silence.)",
			"No Quest: trailer? In THIS dungeon? Claude Dammit Opus! (Add 'Quest: none' to silence.)",
			"Claude Dammit Opus! Even Mongo tags his kills, coder. (Add 'Quest: none' to silence.)",
			"A trailerless commit drifts by like a ghost. The System hates ghosts. Claude Dammit Opus! (Add 'Quest: none' to silence.)",
			"Claude Dammit Opus! Princess Donut would never commit without attribution. She demands attribution for everything. (Add 'Quest: none' to silence.)",
		},
		keyEmptyList: {
			"No quests. The dungeon is quiet. Too quiet.",
			"Zero side quests. Either you're finished or you're doomed.",
			"An empty quest board. The System refreshes the page. Still empty. Suspicious.",
			"No quests found. Either you're a legend, coder, or you haven't looked under the furniture.",
			"Zero quests. The audience changes the channel. Win them back.",
			"The board is bare. Mordecai says enjoy it — this never lasts past breakfast.",
			"Nothing here but tumbleweeds and the faint smell of finished work. Or unstarted work. Hard to tell.",
			"New achievement! Inbox Zero, Dungeon Edition! Reward: the creeping certainty you forgot something.",
			"No quests. Princess Donut is bored. A bored Donut is a dangerous Donut.",
			"The ledger is empty. The System double-checks. The System triple-checks. Huh. Carry on.",
			"Quiet board, coder. In the dungeon, quiet always comes right before the mimic bites.",
			"No outstanding quests. Mongo sniffs the ledger and finds nothing. Not even crumbs.",
		},
		keyInitialized: {
			"side-quest online. Welcome to the floor, coder.",
			"The System boots up. Let the crawl begin.",
			"Ding! A new ledger is born. Welcome to the show, coder. If you get stuck — and you will — file a quest.",
			"The dungeon recognizes this repository. Your quests will be recorded, your excuses cataloged.",
			"Initialization complete. The System has moved in and rearranged the furniture. You'll get used to it.",
			"New achievement! Grand Opening! This repo now has a quest ledger. Reward: accountability. Sorry.",
			"Ledger installed. Mordecai suggests you start with something easy. Mordecai has met you.",
			"The orphan ref stirs to life. It's not haunted. It's barely haunted.",
			"side-quest is live. The sponsors have set up folding chairs. They brought snacks. Begin.",
			"The System carves refs/side-quest into the repo. Your branches remain untouched. The System keeps its promises. Mostly.",
			"Welcome to the ledger, coder. First rule: everything gets written down. Second rule: see the first rule.",
			"Boot sequence complete. Princess Donut has claimed the README as her throne.",
		},
		keyHooksInstalled: {
			"Hooks installed in %s. The System now watches your commits.",
			"Git hooks wired into %s. Nowhere to hide, coder.",
			"Ding! Hooks planted in %s. Every commit now walks past the cameras.",
			"The System wires tripwires into %s. Purely for bookkeeping. Mostly for bookkeeping.",
			"Hooks live in %s. Mordecai calls it 'quality control.' The audience calls it 'surveillance.' Both are right.",
			"New achievement! Under New Management! Hooks installed in %s. Reward: automatic paper trails.",
			"%s is bugged. The good kind of bugged. The kind that files paperwork for you.",
			"Commit hooks armed in %s. Try to look natural, coder.",
			"The System threads its tendrils into %s. It promises to only use them for good. It crosses its heart. It has no heart.",
			"Hooks in %s: active. Mongo guards the exit. There is no exit.",
			"Every commit in %s now gets read, judged, and lovingly filed. Mostly judged.",
			"Installation complete: %s. Princess Donut approved the paperwork by sitting on it.",
		},
		keyNoteAdded: {
			"Noted on %s. The System files it away.",
			"A line added to %s's record. The audience takes notes too.",
			"Ding! Note appended to %s. The ledger grows a little wiser. You, presumably, too.",
			"Scribbled onto %s. The System's handwriting is impeccable. Yours is being generously transcribed.",
			"New achievement! Marginalia! You annotated %s. Reward: context your future self will actually thank you for.",
			"%s gains a footnote. Historians will argue about it for minutes.",
			"Note logged on %s. Mordecai reads everything. Mordecai judges silently.",
			"The System staples your note to %s. With a real stapler. It enjoyed that.",
			"Addendum filed under %s. The audience appreciates lore. The audience LIVES for lore.",
			"Your words are now part of %s's permanent record, coder. Choose the next ones just as carefully.",
			"%s annotated. Princess Donut skimmed it and declared it 'adequate.' High praise.",
			"Note attached to %s. Mongo sniffed it first. Standard procedure.",
		},
		keyQuestSelected: {
			"%s is your quest now. Now get out there and code, Code, CODE!",
			"Locked in on %s. Now get out there and code, Code, CODE!",
			"Ding! %s is now your active quest. The cameras swivel. Make it good.",
			"%s locked in. Every commit from here on wears its name. No pressure. Some pressure.",
			"The System pins %s to your chest like a badge. Or a target. Depends on the floor.",
			"%s selected. Mordecai says focus wins floors. Then he went back to his crafting bench.",
			"You are now questing on %s. The odds boards flutter with fresh wagers.",
			"%s: current. The audience starts a chant. It's your name. It's mostly your name.",
			"All eyes on %s, coder. The sponsors smell a montage.",
			"New achievement! Singular Focus! %s is your one and only. Reward: fewer excuses.",
			"%s takes the spotlight. Princess Donut insists on being in frame anyway.",
			"Current quest: %s. Mongo bounces with anticipation. Do not disappoint Mongo.",
		},
		keyLocalOnlySync: {
			"Local-only mode: your quests stay in the vault. The System syncs nothing, coder.",
			"This dungeon is off the grid — local-only. Nothing leaves, nothing enters.",
			"Local-only engaged. Your side quests are yours alone; the sponsors get nothing.",
			"Local-only mode. What happens in this repo stays in this repo. The System respects a good vault.",
			"Sync skipped: this dungeon runs off the books. The sponsors hate it. That's half the fun.",
			"No sync today, coder. Your quests are a private show — audience of one.",
			"The System checks the exits. Sealed. Local-only, as ordered. Nothing gets out, not even gossip.",
			"Ding! Local-only honored. Your secrets remain secrets. The System pinky-swears.",
			"This ledger doesn't phone home. The System finds that refreshing, honestly. Fewer forms.",
			"Nothing pushed, nothing pulled. Off-grid questing: the survivalist build.",
			"Local-only: engaged. Mordecai approves. He never trusted the network anyway.",
			"Sync suppressed. Even Princess Donut can't leak what never leaves the vault.",
			"Your quests stay home today. Mongo stands guard at the remote. Good boy.",
		},
		keyExported: {
			"%d quests spilled into %s. The archive grows, coder.",
			"Exported %d side quests to %s. The System keeps a copy; so should you.",
			"%d objectives etched into %s. Nothing is ever truly deleted.",
			"Ding! %d quests exported to %s. The scribes worked through the night. They're unionizing.",
			"%d quests copied into %s. The System kept the originals. The System always keeps the originals.",
			"New achievement! Archivist! %d quests preserved in %s. Reward: a backup you'll be smug about later.",
			"The vault doors open: %d quests march into %s in single file. Orderly. Unsettling.",
			"%d quests now live in %s. Mordecai says paper burns but ledgers are forever. He's fun at parties.",
			"Export complete: %d quests to %s. The audience demands a director's cut.",
			"%d quests carved into %s. Future archaeologists will be so confused.",
			"The System photocopies %d quests into %s. It made a second copy for the sponsors. Sorry.",
			"%d quests shipped to %s. Princess Donut supervised. Supervision means napping nearby.",
			"%d quests delivered to %s. Mongo carried them gently. Mostly gently.",
		},
		keyReclassified: {
			"%s reclassified. The System revises its dossier.",
			"New designation for %s. The audience adjusts its bets.",
			"Ding! %s reclassified. The System updates the dossier and shreds the old one dramatically.",
			"%s wears a new label now. Same quest, fresh paint. The audience pretends to notice.",
			"New achievement! Taxonomy! You reclassified %s. Reward: the fleeting illusion of control.",
			"The System re-stamps %s. The stamp is very official. The ink is red. Everything here is red.",
			"%s gets a new designation. Mordecai says classification is half the battle. The other half is the battle.",
			"%s: reshuffled in the great filing cabinet. The cabinet growls. Standard.",
			"Paperwork updated on %s. The sponsors adjust their marketing accordingly.",
			"%s reclassified. Princess Donut demanded a reclassification too. She is now 'Empress.'",
			"The odds boards recalculate %s. The numbers move. The house still wins.",
			"%s: category changed. Mongo did not care. Mongo just wants to see the quest die.",
		},
		keyUpdated: {
			"%s updated. The record shifts; nothing escapes the ledger, coder.",
			"Details on %s rewritten. The System notes the edit.",
			"Ding! %s revised. The ledger accepts your edits. The ledger remembers the old version anyway.",
			"%s updated. History is written by the committers, coder.",
			"New achievement! Second Draft! You edited %s. Reward: marginally better paperwork.",
			"The System applies your changes to %s and initials every page. Thorough. Unnervingly thorough.",
			"%s gets a facelift. The audience votes: improvement. The vote was close.",
			"Edits landed on %s. Mordecai proofread. He found things. He always finds things.",
			"%s amended. The old wording has been sent to live on a farm upstate.",
			"Revision logged on %s. The sponsors prefer the drama of the original, but fine.",
			"%s: updated. Princess Donut approved the changes without reading them. Leadership.",
			"The System refreshes %s. Somewhere, a stale cache weeps.",
		},
		keyLinked: {
			"Commit %s bound to its quest. The chain tightens.",
			"%s enters the ledger. The System logs the deed, coder.",
			"Ding! Commit %s chained to its quest. The paperwork is airtight. The System checked twice.",
			"%s joins the record. Every deed logged, every deed judged. Mostly logged.",
			"New achievement! Chain of Custody! Commit %s is linked. Reward: an alibi.",
			"The System welds %s to the ledger. Sparks fly. Safety goggles were worn.",
			"%s: attached. The audience loves receipts, coder. Everyone loves receipts.",
			"Commit %s takes its place in the chain. The chain rattles approvingly.",
			"%s filed and cross-referenced. Mordecai's filing system remains undefeated.",
			"The ledger swallows %s whole. Burp. Excuse the ledger.",
			"%s linked. Princess Donut bats the commit into place. Teamwork.",
			"Commit %s is on the record. Mongo notarized it with a paw print.",
		},
		keyRelinked: {
			"%s relinked after the rebase. The System reconciles history.",
			"Repointed %s to its true commit. Continuity restored, coder.",
			"Ding! %s repointed after the rebase. The System pretends history was always this way. Play along.",
			"%s relinked. The timeline heals. The scars are cosmetic. Probably.",
			"New achievement! Continuity Editor! %s survives the rebase. Reward: a tidy history and a mild headache.",
			"The System splices %s back into the record. Nobody will notice the cut. Nobody official.",
			"%s reconciled. Rebases rewrite history; the ledger just rewrites the footnotes.",
			"History shifted; %s kept up. Mordecai says only amateurs lose the paper trail.",
			"%s: relinked. The audience rewinds the tape and, yes, it all checks out now.",
			"The old sha is gone; long live the new sha. %s stands corrected.",
			"%s repointed. Princess Donut declares the timeline 'fixed, and also boring now.'",
			"Rebase absorbed. %s never even felt it. The System is that good, coder.",
		},
		keyUnlinked: {
			"A commit cut loose from %s. The ledger forgets, this once.",
			"%s unlinked. The System strikes a line from the record.",
			"Ding! A commit released from %s. The chain is one link lighter. It jingles differently now.",
			"The System snips a commit off %s with tiny golden scissors. Ceremony matters.",
			"New achievement! Conscious Uncoupling! A commit and %s have parted ways. Reward: a cleaner ledger.",
			"%s lets one go. The commit walks free. The audience waves tiny handkerchiefs.",
			"One commit struck from %s's record. Mordecai says even ledgers deserve erasers.",
			"%s: minus one commit. The paperwork sighs with relief.",
			"The bond is severed. %s and that commit will always have the changelog.",
			"A commit exits %s's story. It was miscast anyway.",
			"%s unlinked. Princess Donut never liked that commit. She says so. Loudly.",
			"The System removes a commit from %s and pats the ledger flat. There. Better.",
		},
	},
}
